### ISSUE TITLE
require() doesn't work

### ISSUE THREAD

**Issue by haoliangyu** [haoliangyu/pg-reactive#2]
It will throw an error when initializing the database connection.

```
TypeError: pgrx is not a constructor
    at Object.<anonymous> (/home/haoliang/Desktop/pg-compare/index.js:46:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by haoliangyu** [comment]
fix with v0.3.2
